name: 'Build and push Docker image'
description: 'Composite action to build and push a Docker image to a registry.'

inputs:
  image:
    description: "Name of the Docker image"
    required: true
    default: ${{ github.repository }}
  registry:
    description: "Address of the Docker registry"
    required: true
    default: ghcr.io
  username:
    description: "Username for the Docker registry"
    required: true
    default: ${{ github.actor }}
  password:
    description: "Password for the Docker registry"
    required: true
  platforms:
    description: "Target platforms for the Docker image"
    required: true
    default: linux/amd64

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
