name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with credentials
        uses: dioptra-io/publish-docker-action@main
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          push: true
      - name: Test without credentials
        uses: dioptra-io/publish-docker-action@main
        with:
          push: false

